[platformio]
default_envs = esp32c3

[env]
lib_ldf_mode = deep+
build_flags =
    -std=gnu++17

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
lib_deps =
    https://github.com/ttlappalainen/NMEA2000.git
    https://github.com/ttlappalainen/NMEA2000_esp32.git
build_flags =
    ${env.build_flags}
    -D BATTERYSENTINEL_FIRMWARE=1

[env:native]
platform = native
test_framework = unity
test_build_src = no
build_flags =
    ${env.build_flags}
    -D BATTERYSENTINEL_NATIVE=1
